#!/usr/bin/env bash
# here the comment will go!
# trap: signal to be recieved
echo $$ >> /var/run/myscript.pid
trap "echo Y U no love me?!" SIGINT
trap "echo I hate the kill command && rm -rf /var/run/holbertonscript.pid; exit" SIGTERM SIGQUIT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
