#!/usr/bin/env bash
# Bash script for create a Fizz Buzz
a=1
while [ $a -le 100 ]
do
	if [ $((a % 15)) == 0 ];
	then
		echo "FizzBuzz"

	elif [ $((a % 5)) == 0 ];
	then
		echo "Buzz"

	elif [ $((a % 3)) == 0 ];
	then
		echo "Fizz"
	else
		echo $a
	fi
	((a++))
done
