#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and other features
a=0
while [ $a -le 9 ]
do
	if [ $a -eq 3 ]
	then
		echo "bad luck"
	elif [ $a -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((a++))
done
